version: '3.9'

services:
  agenda-app:
    container_name: agenda-app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - agenda-db

  agenda-db:
    container_name: agenda-db
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env